function Main
%Add Folder to search path
addpath(genpath('Menu_Functions'),...
    genpath('Tab Functions'),...
    genpath('Progress_Functions'),...
    genpath('Analysis Functions'),...
    genpath('Movie Functions'))
close all
clearvars -global

%% Initialize Global Variables
%Figure Variable
global MainFig;
%Variables to save data
global M_File;
%Variable for Summary
global Summary
%Variable To Store Video Information
global Video_Temp

%% Initialize Main Window
% Initialize Figure
MainFig.Figure=figure;

% Get screen resolution
SC = get(0, 'ScreenSize');
MainFig.MaxMonitorX = SC(3);
MainFig.MaxMonitorY = SC(4);
clear SC

%Set scaling factor for window
MainFig.Main_scaling_factorX=0.9;
MainFig.Main_scaling_factorY=MainFig.Main_scaling_factorX*0.9;

%Set figure size and position
set(MainFig.Figure, 'Position', ...
    [(1-MainFig.Main_scaling_factorX)/2*MainFig.MaxMonitorX ...
    (1-MainFig.Main_scaling_factorY)/2*MainFig.MaxMonitorY ...
    MainFig.MaxMonitorX*MainFig.Main_scaling_factorX ...
    MainFig.MaxMonitorY*MainFig.Main_scaling_factorY]);

%Set figure menu bar
set(MainFig.Figure,'MenuBar','none');

%Set Point "Menu"
MainFig.Menu=uimenu('Label','Menu');
uimenu(MainFig.Menu,'Label','Load Trajectory File','Callback',@Load_Trajectory_File);
uimenu(MainFig.Menu,'Label','Load .m File','Separator','on','Callback',@Load_m_File,'Accelerator','L');
uimenu(MainFig.Menu,'Label','Save Current .m File','Callback',@Save_m_File,'Accelerator','S');
uimenu(MainFig.Menu,'Label','Quit','Separator','on');

%Set figure toolbar
set(MainFig.Figure, 'Toolbar','figure')

%Set figure name
set(MainFig.Figure, 'Name','Zebrafish Analysis')
set(MainFig.Figure, 'NumberTitle','off')

%% Create Table Indicator to display all analysis which are performed
MainFig.Panel.Handle=uipanel(MainFig.Figure,'Position',[0.005 0.005 0.185 0.99]);
MainFig.Panel.Table=uitable(MainFig.Panel.Handle,'Units','Normalized', ...
    'Position',[0.005 0.505 0.99 0.49]);
set(MainFig.Panel.Table,'ColumnName',{'Analysis Step' 'Done'});
set(MainFig.Panel.Table,'Units','Pixel')
temp=get(MainFig.Panel.Table,'Position');
Columnwidth=temp(3)/2.25;
set(MainFig.Panel.Table,'ColumnWidth',{Columnwidth});
set(MainFig.Panel.Table,'Units','Normalized')
Progress_Default_Data;

%% Create Tab Control
MainFig.Maintab.Handle=uitabgroup(MainFig.Figure,'Position',[0.195 0.005 0.8 0.99],'SelectionChangedFcn',@Tab_Selection);
MainFig.Maintab.Tab1.Handle=uitab(MainFig.Maintab.Handle,'Title','Trajectory');
MainFig.Maintab.Tab2.Handle=uitab(MainFig.Maintab.Handle,'Title','Identify Active States');
MainFig.Maintab.Tab3.Handle=uitab(MainFig.Maintab.Handle,'Title','Population Identification');
MainFig.Maintab.Tab5.Handle=uitab(MainFig.Maintab.Handle,'Title','Video Analysis & Rendering');
MainFig.Maintab.Tab6.Handle=uitab(MainFig.Maintab.Handle,'Title','Analyse Repetitive Data');
MainFig.Maintab.Tab4.Handle=uitab(MainFig.Maintab.Handle,'Title','Summarize Trajectory Data');

%% Fill Tab "Trajectory"
MainFig.Maintab.Tab1.Panel.Handle=uipanel('Parent',MainFig.Maintab.Tab1.Handle,'Position',[0 0 1 1]);

%Create figure for trajectory plot
MainFig.Maintab.Tab1.Panel.Fig1=axes('Parent',MainFig.Maintab.Tab1.Panel.Handle,'Position',[0.0525 0.2525 0.93 0.7]);
MainFig.Maintab.Tab1.Panel.Fig1.Title.String='Trajectory';
MainFig.Maintab.Tab1.Panel.Fig1.XLabel.String='X [µm]';
MainFig.Maintab.Tab1.Panel.Fig1.YLabel.String='Y [µm]';
MainFig.Maintab.Tab1.Panel.Fig1.ZLabel.String='Z [µm]';

%Create Table for trajectory information
MainFig.Maintab.Tab1.Panel.Table=uitable(MainFig.Maintab.Tab1.Panel.Handle,'Units','Normalized',...
    'Position',[0.0525 0.0525 0.8 0.1]);
Trajectory_Table_Default_Data;
set(MainFig.Maintab.Tab1.Panel.Table,'Units','Pixel')
temp=get(MainFig.Maintab.Tab1.Panel.Table,'Position');
Columnwidth=temp(3)/8;
set(MainFig.Maintab.Tab1.Panel.Table,'ColumnWidth',{Columnwidth Columnwidth Columnwidth});
set(MainFig.Maintab.Tab1.Panel.Table,'Units','Normalized')

%% Fill Tab "Identify Active States"
MainFig.Maintab.Tab2.Panel.Handle=uipanel('Parent',MainFig.Maintab.Tab2.Handle,'Position',[0 0 1 1]);

%Create Tab Control to Plot Trajectory with active and Passive Parts +
%Correlation Amplitude with Treshold
MainFig.Maintab.Tab2.Panel.Tab.Handle=uitabgroup(MainFig.Maintab.Tab2.Panel.Handle,'Position',[0.01 0.15 0.98 0.84]);
MainFig.Maintab.Tab2.Panel.Tab.Tab1.Handle=uitab(MainFig.Maintab.Tab2.Panel.Tab.Handle,'Title','Active + Passive States');
MainFig.Maintab.Tab2.Panel.Tab.Tab2.Handle=uitab(MainFig.Maintab.Tab2.Panel.Tab.Handle,'Title','Correlation Amplitude');

%Create Figure for trajectory plot
MainFig.Maintab.Tab2.Panel.Tab.Tab1.Fig1=axes('Parent',MainFig.Maintab.Tab2.Panel.Tab.Tab1.Handle,'Position',[0.0525 0.1 0.93 0.85]);
MainFig.Maintab.Tab2.Panel.Tab.Tab1.Fig1.Title.String='Trajectory';
MainFig.Maintab.Tab2.Panel.Tab.Tab1.Fig1.XLabel.String='X [µm]';
MainFig.Maintab.Tab2.Panel.Tab.Tab1.Fig1.YLabel.String='Y [µm]';
MainFig.Maintab.Tab2.Panel.Tab.Tab1.Fig1.ZLabel.String='Z [µm]';

%Create Figure for Correlation Amplitude
MainFig.Maintab.Tab2.Panel.Tab.Tab2.Fig1=axes('Parent',MainFig.Maintab.Tab2.Panel.Tab.Tab2.Handle,'Position',[0.0525 0.1 0.93 0.85]);
MainFig.Maintab.Tab2.Panel.Tab.Tab2.Fig1.Title.String='Correlation Amplitude';
MainFig.Maintab.Tab2.Panel.Tab.Tab2.Fig1.XLabel.String='Orbit #';
MainFig.Maintab.Tab2.Panel.Tab.Tab2.Fig1.YLabel.String='Correlation Amplitude [a.u]';


%Create Textbox for Correlation Window length
MainFig.Maintab.Tab2.Panel.CorrWindEdit=uicontrol(MainFig.Maintab.Tab2.Panel.Handle,...
    'Units','Normalized','Position',[0.055 0.0525 0.15 0.025],...
    'Style','Edit','String','64');
MainFig.Maintab.Tab2.Panel.CorrWindStatic=uicontrol(MainFig.Maintab.Tab2.Panel.Handle,...
    'Units','Normalized','Position',[0.055 0.08 0.15 0.025],...
    'Style','Text','String','Correlation Window');

%Create Textbox for Orbit Treshold
MainFig.Maintab.Tab2.Panel.OrbitTreshEdit=uicontrol(MainFig.Maintab.Tab2.Panel.Handle,...
    'Units','Normalized','Position',[0.22 0.0525 0.15 0.025],...
    'Style','Edit','String','150');
MainFig.Maintab.Tab2.Panel.OrbitTreshStatic=uicontrol(MainFig.Maintab.Tab2.Panel.Handle,...
    'Units','Normalized','Position',[0.22 0.08 0.15 0.025],...
    'Style','Text','String','Orbit Treshold [ms]');

%Create Textbox for Active Treshold
MainFig.Maintab.Tab2.Panel.ActiveTreshEdit=uicontrol(MainFig.Maintab.Tab2.Panel.Handle,...
    'Units','Normalized','Position',[0.385 0.0525 0.15 0.025],...
    'Style','Edit','String','5');
MainFig.Maintab.Tab2.Panel.ActiveTreshStatic=uicontrol(MainFig.Maintab.Tab2.Panel.Handle,...
    'Units','Normalized','Position',[0.385 0.08 0.15 0.025],...
    'Style','Text','String','Treshold = Mean + x*Std');

%Create Buttongroup to choose between parfor and for
MainFig.Maintab.Tab2.Panel.ParforSelect.Handle=uibuttongroup(MainFig.Maintab.Tab2.Panel.Handle, ...
    'Units','Normalized','Position', [0.55 0.035 0.15 0.07], ...
    'Title', 'Correlation Loop Mode');
MainFig.Maintab.Tab2.Panel.ParforSelect.Select1= uicontrol(MainFig.Maintab.Tab2.Panel.ParforSelect.Handle,...
    'Style','radiobutton','String','For','Units','Normalized','Position',[0.01 0.01 0.49 0.9],...
    'HandleVisibility','off');
MainFig.Maintab.Tab2.Panel.ParforSelect.Select2= uicontrol(MainFig.Maintab.Tab2.Panel.ParforSelect.Handle,...
    'Style','radiobutton','String','Parfor','Units','Normalized','Position',[0.5 0.01 0.49 0.9],...
    'HandleVisibility','off');


%Create Button to Start Correlation
MainFig.Maintab.Tab2.Panel.CorrButton=uicontrol(MainFig.Maintab.Tab2.Panel.Handle,...
    'Style','pushbutton','String','Start Correlation', ...
    'Units','Normalized','Position', [0.72 0.0425 0.15 0.05], ...
    'Callback',@Start_Correlation);

%% Fill Tab "Population Identification"
MainFig.Maintab.Tab3.Panel.Handle=uipanel('Parent',MainFig.Maintab.Tab3.Handle,'Position',[0 0 1 1]);


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%Create Tab Control to Plot Trajectory with active and Passive Parts +
%Correlation Amplitude with Treshold
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
MainFig.Maintab.Tab3.Panel.Tab.Handle=uitabgroup(MainFig.Maintab.Tab3.Panel.Handle,'Position',[0.01 0.125 0.98 0.85]);
MainFig.Maintab.Tab3.Panel.Tab.Tab1.Handle=uitab(MainFig.Maintab.Tab3.Panel.Tab.Handle,'Title','MLE ');
MainFig.Maintab.Tab3.Panel.Tab.Tab2.Handle=uitab(MainFig.Maintab.Tab3.Panel.Tab.Handle,'Title','Population Trajectory');
MainFig.Maintab.Tab3.Panel.Tab.Tab3.Handle=uitab(MainFig.Maintab.Tab3.Panel.Tab.Handle,'Title','Histograms');
MainFig.Maintab.Tab3.Panel.Tab.Tab4.Handle=uitab(MainFig.Maintab.Tab3.Panel.Tab.Handle,'Title','Movement Behaviour Pattern');




%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%Fill Tab 1 - MLE Fit
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
MainFig.Maintab.Tab3.Panel.Tab.Tab1.Panel=uipanel('Parent',MainFig.Maintab.Tab3.Panel.Tab.Tab1.Handle,'Position',[0 0 1 1]);




%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%Create Buttongroup to choose between one or two populations for each
%direction.
%Retrograd
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
MainFig.Maintab.Tab3.Panel.Retroselect.Handle=uibuttongroup(MainFig.Maintab.Tab3.Panel.Handle, ...
    'Units','Normalized','Position', [0.1 0.035 0.14 0.07], ...
    'Title', '# of Retrograd Populations');
MainFig.Maintab.Tab3.Panel.Retroselect.Select1= uicontrol(MainFig.Maintab.Tab3.Panel.Retroselect.Handle,...
    'Style','radiobutton','String','One','Units','Normalized','Position',[0.01 0.01 0.49 0.9],...
    'HandleVisibility','off');
MainFig.Maintab.Tab3.Panel.Retroselect.Select2= uicontrol(MainFig.Maintab.Tab3.Panel.Retroselect.Handle,...
    'Style','radiobutton','String','Two','Units','Normalized','Position',[0.5 0.01 0.49 0.9],...
    'HandleVisibility','off');

MainFig.Maintab.Tab3.Panel.Retrospeed.Handle=uibuttongroup(MainFig.Maintab.Tab3.Panel.Handle, ...
    'Units','Normalized','Position', [0.25 0.035 0.14 0.07], ...
    'Title', 'Retrograd Population');
MainFig.Maintab.Tab3.Panel.Retrospeed.Fast= uicontrol(MainFig.Maintab.Tab3.Panel.Retrospeed.Handle,...
    'Style','radiobutton','String','Fast','Units','Normalized','Position',[0.01 0.01 0.49 0.9],...
    'HandleVisibility','off');
MainFig.Maintab.Tab3.Panel.Retrospeed.Slow= uicontrol(MainFig.Maintab.Tab3.Panel.Retrospeed.Handle,...
    'Style','radiobutton','String','Slow','Units','Normalized','Position',[0.5 0.01 0.49 0.9],...
    'HandleVisibility','off');


%Anterograd
MainFig.Maintab.Tab3.Panel.Anteroselect.Handle=uibuttongroup(MainFig.Maintab.Tab3.Panel.Handle, ...
    'Units','Normalized','Position', [0.6 0.035 0.14 0.07], ...
    'Title', '# of Anterograd Populations');
MainFig.Maintab.Tab3.Panel.Anteroselect.Select1= uicontrol(MainFig.Maintab.Tab3.Panel.Anteroselect.Handle,...
    'Style','radiobutton','String','One','Units','Normalized','Position',[0.01 0.01 0.49 0.9],...
    'HandleVisibility','off');
MainFig.Maintab.Tab3.Panel.Anteroselect.Select2= uicontrol(MainFig.Maintab.Tab3.Panel.Anteroselect.Handle,...
    'Style','radiobutton','String','Two','Units','Normalized','Position',[0.5 0.01 0.49 0.9],...
    'HandleVisibility','off');


MainFig.Maintab.Tab3.Panel.Anterospeed.Handle=uibuttongroup(MainFig.Maintab.Tab3.Panel.Handle, ...
    'Units','Normalized','Position', [0.75 0.035 0.14 0.07], ...
    'Title', 'Anterograd Population');
MainFig.Maintab.Tab3.Panel.Anterospeed.Fast= uicontrol(MainFig.Maintab.Tab3.Panel.Anterospeed.Handle,...
    'Style','radiobutton','String','Fast','Units','Normalized','Position',[0.01 0.01 0.49 0.9],...
    'HandleVisibility','off');
MainFig.Maintab.Tab3.Panel.Anterospeed.Slow= uicontrol(MainFig.Maintab.Tab3.Panel.Anterospeed.Handle,...
    'Style','radiobutton','String','Slow','Units','Normalized','Position',[0.5 0.01 0.49 0.9],...
    'HandleVisibility','off');






%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%Create Button to start MLE Fit
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
MainFig.Maintab.Tab3.Panel.MLEButton=uicontrol(MainFig.Maintab.Tab3.Panel.Handle,...
    'Style','pushbutton','String','Start MLE Fit', ...
    'Units','Normalized','Position', [0.42 0.0425 0.15 0.05], ...
    'Callback',@Start_MLE_Fit);




%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%Create MLE Figures
%Retrograd
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
MainFig.Maintab.Tab3.Panel.Tab.Tab1.FigRetroVel=axes('Parent',MainFig.Maintab.Tab3.Panel.Tab.Tab1.Panel,'Position',[0.05 0.08 0.4 0.38]);
MainFig.Maintab.Tab3.Panel.Tab.Tab1.FigRetroVel.Title.String='Retrograde Velocity';
MainFig.Maintab.Tab3.Panel.Tab.Tab1.FigRetroHist=axes('Parent',MainFig.Maintab.Tab3.Panel.Tab.Tab1.Panel,'Position',[0.05 0.58 0.4 0.38]);
MainFig.Maintab.Tab3.Panel.Tab.Tab1.FigRetroHist.Title.String='Retrograde Velocity Histogram';



%Anterograd
MainFig.Maintab.Tab3.Panel.Tab.Tab1.FigAnteroVel=axes('Parent',MainFig.Maintab.Tab3.Panel.Tab.Tab1.Panel,'Position',[0.55 0.08 0.4 0.38]);
MainFig.Maintab.Tab3.Panel.Tab.Tab1.FigAnteroVel.Title.String='Anterograd Velocity';
MainFig.Maintab.Tab3.Panel.Tab.Tab1.FigAnteroHist=axes('Parent',MainFig.Maintab.Tab3.Panel.Tab.Tab1.Panel,'Position',[0.55 0.58 0.4 0.38]);
MainFig.Maintab.Tab3.Panel.Tab.Tab1.FigAnteroHist.Title.String='Anterograd Velocity Histogram';




%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%Fill Tab 2 - Create Figure for Population Trajectory plot
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
MainFig.Maintab.Tab3.Panel.Tab.Tab2.Fig1=axes('Parent',MainFig.Maintab.Tab3.Panel.Tab.Tab2.Handle,'Position',[0.0525 0.1 0.93 0.85]);
MainFig.Maintab.Tab3.Panel.Tab.Tab2.Fig1.Title.String='Trajectory';
MainFig.Maintab.Tab3.Panel.Tab.Tab2.Fig1.XLabel.String='X [µm]';
MainFig.Maintab.Tab3.Panel.Tab.Tab2.Fig1.YLabel.String='Y [µm]';
MainFig.Maintab.Tab3.Panel.Tab.Tab2.Fig1.ZLabel.String='Z [µm]';



%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%Fill Tab 3 - Histograms
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
MainFig.Maintab.Tab3.Panel.Tab.Tab3.Tab.Handle=uitabgroup(MainFig.Maintab.Tab3.Panel.Tab.Tab3.Handle,'Position',[0.01 0.01 0.98 0.98]);
MainFig.Maintab.Tab3.Panel.Tab.Tab3.Tab.Tab1.Handle=uitab(MainFig.Maintab.Tab3.Panel.Tab.Tab3.Tab.Handle,'Title','Orbit Displacement ');
MainFig.Maintab.Tab3.Panel.Tab.Tab3.Tab.Tab2.Handle=uitab(MainFig.Maintab.Tab3.Panel.Tab.Tab3.Tab.Handle,'Title','Run Length [µm]');
MainFig.Maintab.Tab3.Panel.Tab.Tab3.Tab.Tab3.Handle=uitab(MainFig.Maintab.Tab3.Panel.Tab.Tab3.Tab.Handle,'Title','Duration [s]');


%Create Figures for Orbit Displacement
MainFig.Maintab.Tab3.Panel.Tab.Tab3.Tab.Tab1.Fig1=axes('Parent',MainFig.Maintab.Tab3.Panel.Tab.Tab3.Tab.Tab1.Handle,'Position',[0.05 0.1 0.9 0.8]);
MainFig.Maintab.Tab3.Panel.Tab.Tab3.Tab.Tab1.Fig1.Title.String='Orbit Displacement';
MainFig.Maintab.Tab3.Panel.Tab.Tab3.Tab.Tab1.Fig1.XLabel.String='Displacement [nm]';
MainFig.Maintab.Tab3.Panel.Tab.Tab3.Tab.Tab1.Fig1.YLabel.String='Normalized # of Events';

%Create Figures for Run length(µm)
MainFig.Maintab.Tab3.Panel.Tab.Tab3.Tab.Tab2.Fig1=axes('Parent',...
    MainFig.Maintab.Tab3.Panel.Tab.Tab3.Tab.Tab2.Handle,'Position',[0.05 0.11 0.4 0.33]);
MainFig.Maintab.Tab3.Panel.Tab.Tab3.Tab.Tab2.Fig1.Title.String='Retrograde Slow';
MainFig.Maintab.Tab3.Panel.Tab.Tab3.Tab.Tab2.Fig1.XLabel.String='Run length [µm]';
MainFig.Maintab.Tab3.Panel.Tab.Tab3.Tab.Tab2.Fig1.YLabel.String='# of Events';
MainFig.Maintab.Tab3.Panel.Tab.Tab3.Tab.Tab2.Fig2=axes('Parent',...
    MainFig.Maintab.Tab3.Panel.Tab.Tab3.Tab.Tab2.Handle,'Position',[0.05 0.61 0.4 0.33]);
MainFig.Maintab.Tab3.Panel.Tab.Tab3.Tab.Tab2.Fig2.Title.String='Retrograde Fast';
MainFig.Maintab.Tab3.Panel.Tab.Tab3.Tab.Tab2.Fig2.XLabel.String='Run length [µm]';
MainFig.Maintab.Tab3.Panel.Tab.Tab3.Tab.Tab2.Fig2.YLabel.String='# of Events';
MainFig.Maintab.Tab3.Panel.Tab.Tab3.Tab.Tab2.Fig3=axes('Parent',...
    MainFig.Maintab.Tab3.Panel.Tab.Tab3.Tab.Tab2.Handle,'Position',[0.55 0.11 0.4 0.33]);
MainFig.Maintab.Tab3.Panel.Tab.Tab3.Tab.Tab2.Fig3.Title.String='Anterograde Slow';
MainFig.Maintab.Tab3.Panel.Tab.Tab3.Tab.Tab2.Fig3.XLabel.String='Run length [µm]';
MainFig.Maintab.Tab3.Panel.Tab.Tab3.Tab.Tab2.Fig3.YLabel.String='# of Events';
MainFig.Maintab.Tab3.Panel.Tab.Tab3.Tab.Tab2.Fig4=axes('Parent',...
    MainFig.Maintab.Tab3.Panel.Tab.Tab3.Tab.Tab2.Handle,'Position',[0.55 0.61 0.4 0.33]);
MainFig.Maintab.Tab3.Panel.Tab.Tab3.Tab.Tab2.Fig4.Title.String='Anterograde Fast';
MainFig.Maintab.Tab3.Panel.Tab.Tab3.Tab.Tab2.Fig4.XLabel.String='Run length [µm]';
MainFig.Maintab.Tab3.Panel.Tab.Tab3.Tab.Tab2.Fig4.YLabel.String='# of Events';

%Create Textboxes for Mean Values [µm]
MainFig.Maintab.Tab3.Panel.Tab.Tab3.Tab.Tab2.Text1=uicontrol(...
    MainFig.Maintab.Tab3.Panel.Tab.Tab3.Tab.Tab2.Handle,'Units','Normalized',...
    'Position', [0.35 0 0.1 0.05],'Style','text','String','Mean= ~ µm');
MainFig.Maintab.Tab3.Panel.Tab.Tab3.Tab.Tab2.Text2=uicontrol(...
    MainFig.Maintab.Tab3.Panel.Tab.Tab3.Tab.Tab2.Handle,'Units','Normalized',...
    'Position', [0.35 0.5 0.1 0.05],'Style','text','String','Mean= ~ µm');
MainFig.Maintab.Tab3.Panel.Tab.Tab3.Tab.Tab2.Text3=uicontrol(...
    MainFig.Maintab.Tab3.Panel.Tab.Tab3.Tab.Tab2.Handle,'Units','Normalized',...
    'Position', [0.85 0 0.1 0.05],'Style','text','String','Mean= ~ µm');
MainFig.Maintab.Tab3.Panel.Tab.Tab3.Tab.Tab2.Text4=uicontrol(...
    MainFig.Maintab.Tab3.Panel.Tab.Tab3.Tab.Tab2.Handle,'Units','Normalized',...
    'Position', [0.85 0.5 0.1 0.05],'Style','text','String','Mean= ~ µm');


%Create Figures for Duration [s]
MainFig.Maintab.Tab3.Panel.Tab.Tab3.Tab.Tab3.Fig1=axes('Parent',...
    MainFig.Maintab.Tab3.Panel.Tab.Tab3.Tab.Tab3.Handle,'Position',[0.05 0.11 0.4 0.33]);
MainFig.Maintab.Tab3.Panel.Tab.Tab3.Tab.Tab3.Fig1.Title.String='Retrograde Slow';
MainFig.Maintab.Tab3.Panel.Tab.Tab3.Tab.Tab3.Fig1.XLabel.String='Duration [s]';
MainFig.Maintab.Tab3.Panel.Tab.Tab3.Tab.Tab3.Fig1.YLabel.String='# of Events';
MainFig.Maintab.Tab3.Panel.Tab.Tab3.Tab.Tab3.Fig2=axes('Parent',...
    MainFig.Maintab.Tab3.Panel.Tab.Tab3.Tab.Tab3.Handle,'Position',[0.05 0.61 0.4 0.33]);
MainFig.Maintab.Tab3.Panel.Tab.Tab3.Tab.Tab3.Fig2.Title.String='Retrograde Fast';
MainFig.Maintab.Tab3.Panel.Tab.Tab3.Tab.Tab3.Fig2.XLabel.String='Duration [s]';
MainFig.Maintab.Tab3.Panel.Tab.Tab3.Tab.Tab3.Fig2.YLabel.String='# of Events';
MainFig.Maintab.Tab3.Panel.Tab.Tab3.Tab.Tab3.Fig3=axes('Parent',...
    MainFig.Maintab.Tab3.Panel.Tab.Tab3.Tab.Tab3.Handle,'Position',[0.55 0.11 0.4 0.33]);
MainFig.Maintab.Tab3.Panel.Tab.Tab3.Tab.Tab3.Fig3.Title.String='Anterograde Slow';
MainFig.Maintab.Tab3.Panel.Tab.Tab3.Tab.Tab3.Fig3.XLabel.String='Duration [s]';
MainFig.Maintab.Tab3.Panel.Tab.Tab3.Tab.Tab3.Fig3.YLabel.String='# of Events';
MainFig.Maintab.Tab3.Panel.Tab.Tab3.Tab.Tab3.Fig4=axes('Parent',...
    MainFig.Maintab.Tab3.Panel.Tab.Tab3.Tab.Tab3.Handle,'Position',[0.55 0.61 0.4 0.33]);
MainFig.Maintab.Tab3.Panel.Tab.Tab3.Tab.Tab3.Fig4.Title.String='Anterograde Fast';
MainFig.Maintab.Tab3.Panel.Tab.Tab3.Tab.Tab3.Fig4.XLabel.String='Duration [s]';
MainFig.Maintab.Tab3.Panel.Tab.Tab3.Tab.Tab3.Fig4.YLabel.String='# of Events';


%Create Textboxes for Mean Values [s]
MainFig.Maintab.Tab3.Panel.Tab.Tab3.Tab.Tab3.Text1=uicontrol(...
    MainFig.Maintab.Tab3.Panel.Tab.Tab3.Tab.Tab3.Handle,'Units','Normalized',...
    'Position', [0.35 0 0.1 0.05],'Style','text','String','Mean= ~ s');
MainFig.Maintab.Tab3.Panel.Tab.Tab3.Tab.Tab3.Text2=uicontrol(...
    MainFig.Maintab.Tab3.Panel.Tab.Tab3.Tab.Tab3.Handle,'Units','Normalized',...
    'Position', [0.35 0.5 0.1 0.05],'Style','text','String','Mean= ~ s');
MainFig.Maintab.Tab3.Panel.Tab.Tab3.Tab.Tab3.Text3=uicontrol(...
    MainFig.Maintab.Tab3.Panel.Tab.Tab3.Tab.Tab3.Handle,'Units','Normalized',...
    'Position', [0.85 0 0.1 0.05],'Style','text','String','Mean= ~ s');
MainFig.Maintab.Tab3.Panel.Tab.Tab3.Tab.Tab3.Text4=uicontrol(...
    MainFig.Maintab.Tab3.Panel.Tab.Tab3.Tab.Tab3.Handle,'Units','Normalized',...
    'Position', [0.85 0.5 0.1 0.05],'Style','text','String','Mean= ~ s');


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%Fill Tab 4 - Movement Behaviour Pattern
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
MainFig.Maintab.Tab3.Panel.Tab.Tab4.Panel.Handle=uipanel(...
    MainFig.Maintab.Tab3.Panel.Tab.Tab4.Handle,'Position',[0 0 1 1],...
    'HandleVisibility','On');

%Table for Transition Propability
MainFig.Maintab.Tab3.Panel.Tab.Tab4.Panel.Table1=...
    uitable(MainFig.Maintab.Tab3.Panel.Tab.Tab4.Panel.Handle,...
    'Units','Normalized',...
    'Position',[0.005 0.75 0.36 0.22],...
    'Data',[0 0 0 0; 0 0 0 0; 0 0 0 0; 0 0 0 0;],...
    'ColumnName',{'End F. Retro','End F. Antero','End S. Retro','End S. Antero'},...
    'RowName',{'Start Fast Retro','Start Fast Antero','Start Slow Retro','Start Slow Antero'},...
    'ColumnWidth',{'auto' 'auto' 'auto' 'auto' });
MainFig.Maintab.Tab3.Panel.Tab.Tab4.Panel.Table1.Position(3) = ...
    MainFig.Maintab.Tab3.Panel.Tab.Tab4.Panel.Table1.Extent(3);
MainFig.Maintab.Tab3.Panel.Tab.Tab4.Panel.Table1.Position(4) = ...
    MainFig.Maintab.Tab3.Panel.Tab.Tab4.Panel.Table1.Extent(4);
%Description for table Transition Propability
MainFig.Maintab.Tab4.Panel.Tab.Tab2.Tab.Tab4.Panel.Text1=uicontrol(...
    MainFig.Maintab.Tab3.Panel.Tab.Tab4.Panel.Handle,'Units','Normalized',...
    'Position', [0.01 0.95 0.125 0.03],'Style','text','String','Transition Propability',...
    'FontSize',10);

%Table for Transition Time
MainFig.Maintab.Tab3.Panel.Tab.Tab4.Panel.Table2=...
    uitable(MainFig.Maintab.Tab3.Panel.Tab.Tab4.Panel.Handle,...
    'Units','Normalized',...
    'Position',[0.505 0.75 0.36 0.22],...
    'Data',[0 0 0 0; 0 0 0 0; 0 0 0 0; 0 0 0 0;],...
    'ColumnName',{'End F. Retro','End F. Antero','End S. Retro','End S. Antero'},...
    'RowName',{'Start Fast Retro','Start Fast Antero','Start Slow Retro','Start Slow Antero'},...
    'ColumnWidth',{'auto' 'auto' 'auto' 'auto' },...
    'CellSelectionCallback',@Transition_Histogram);
MainFig.Maintab.Tab3.Panel.Tab.Tab4.Panel.Table2.Position(3) = ...
    MainFig.Maintab.Tab3.Panel.Tab.Tab4.Panel.Table2.Extent(3);
MainFig.Maintab.Tab3.Panel.Tab.Tab4.Panel.Table2.Position(4) = ...
    MainFig.Maintab.Tab3.Panel.Tab.Tab4.Panel.Table2.Extent(4);
%Description for table Transition Propability
MainFig.Maintab.Tab4.Panel.Tab.Tab2.Tab.Tab4.Panel.Text2=uicontrol(...
    MainFig.Maintab.Tab3.Panel.Tab.Tab4.Panel.Handle,'Units','Normalized',...
    'Position', [0.51 0.95 0.125 0.03],'Style','text','String','Transition Time [s]',...
    'FontSize',10);

%Create Figure to plot Histograms
MainFig.Maintab.Tab3.Panel.Tab.Tab4.Panel.Fig1=axes('Parent',...
    MainFig.Maintab.Tab3.Panel.Tab.Tab4.Panel.Handle,'Position',[0.05 0.05 0.9 0.6],...
    'xlim',[-0.5 10.5],...
    'Box','on');
%Description for Histogram
MainFig.Maintab.Tab4.Panel.Tab.Tab2.Tab.Tab4.Panel.Text3=uicontrol(...
    MainFig.Maintab.Tab3.Panel.Tab.Tab4.Panel.Handle,'Units','Normalized',...
    'Position', [0.05 0.653 0.35 0.05],'Style','text','String','Transition Time Histogram (Click Transition Time to Plot)',...
    'FontSize',10);

%% Fill Tab "Summarize Trajectory Data"
MainFig.Maintab.Tab4.Panel.Handle=uipanel('Parent',MainFig.Maintab.Tab4.Handle,'Position',[0 0 1 1]);

%Create uitab
MainFig.Maintab.Tab4.Panel.Tab.Handle=uitabgroup(MainFig.Maintab.Tab4.Panel.Handle,'Position',[0.005 0.005 0.99 0.99]);
MainFig.Maintab.Tab4.Panel.Tab.Tab1.Handle=uitab(MainFig.Maintab.Tab4.Panel.Tab.Handle,'Title','Summarize Data');
MainFig.Maintab.Tab4.Panel.Tab.Tab2.Handle=uitab(MainFig.Maintab.Tab4.Panel.Tab.Handle,'Title','Results');


% Fill Tab "Summarize Data"
%Create Table
MainFig.Maintab.Tab4.Panel.Tab.Tab1.Table=uitable(MainFig.Maintab.Tab4.Panel.Tab.Tab1.Handle,...
    'Units','Normalized',...
    'Position',[0.005 0.105 0.99 0.89],...
    'ColumnName',{'Filename','Use File','Direction','Trajectory Length [µm]'},...
    'Data',{'Filename',false, 'Retrograde/Anterograde' '0'},...
    'ColumnEditable',[false true false false],...
    'ColumnWidth',{800 'auto' 200 200});

%Create Button "Select Folder"
MainFig.Maintab.Tab4.Panel.Tab.Tab1.Select=uicontrol(MainFig.Maintab.Tab4.Panel.Tab.Tab1.Handle,...
    'Style','pushbutton','String','Select Folder', ...
    'Units','Normalized','Position', [0.1 0.0225 0.15 0.05], ...
    'Callback',@Select_Folder);

%Create Button "Summarize Data"
MainFig.Maintab.Tab4.Panel.Tab.Tab1.Load=uicontrol(MainFig.Maintab.Tab4.Panel.Tab.Tab1.Handle,...
    'Style','pushbutton','String','Summarize Data', ...
    'Units','Normalized','Position', [0.28 0.0225 0.15 0.05], ...
    'Callback',@Summarize_Data);

%Create Button "Save Summary"
MainFig.Maintab.Tab4.Panel.Tab.Tab1.Save=uicontrol(MainFig.Maintab.Tab4.Panel.Tab.Tab1.Handle,...
    'Style','pushbutton','String','Save Summary', ...
    'Units','Normalized','Position', [0.46 0.0225 0.15 0.05], ...
    'Callback',@Save_Summary);


%Create Buttongroup to choose between parfor and for
MainFig.Maintab.Tab4.Panel.Tab.Tab1.SelectTrajectories.Handle=uibuttongroup(MainFig.Maintab.Tab4.Panel.Tab.Tab1.Handle, ...
    'Units','Normalized','Position', [0.65 0.0225 0.30 0.065], ...
    'Title', 'Trajectory Selection','SelectionChangedFcn',@Trajectory_Selection);
MainFig.Maintab.Tab4.Panel.Tab.Tab1.SelectTrajectories.Select1= uicontrol(MainFig.Maintab.Tab4.Panel.Tab.Tab1.SelectTrajectories.Handle,...
    'Style','radiobutton','String','All Trajectories','Units','Normalized','Position',[0.01 0.01 0.32 0.9],...
    'HandleVisibility','off');
MainFig.Maintab.Tab4.Panel.Tab.Tab1.SelectTrajectories.Select2= uicontrol(MainFig.Maintab.Tab4.Panel.Tab.Tab1.SelectTrajectories.Handle,...
    'Style','radiobutton','String','Only Retrograde','Units','Normalized','Position',[0.35 0.01 0.32 0.9],...
    'HandleVisibility','off');
MainFig.Maintab.Tab4.Panel.Tab.Tab1.SelectTrajectories.Select3= uicontrol(MainFig.Maintab.Tab4.Panel.Tab.Tab1.SelectTrajectories.Handle,...
    'Style','radiobutton','String','Only Anterograde','Units','Normalized','Position',[0.67 0.01 0.32 0.9],...
    'HandleVisibility','off');


%Fill Tab "Results"
MainFig.Maintab.Tab4.Panel.Tab.Tab2.Panel.Handle=uipanel('Parent',...
    MainFig.Maintab.Tab4.Panel.Tab.Tab2.Handle,'Position',[0 0 1 1]);

%Create Tabgroup
MainFig.Maintab.Tab4.Panel.Tab.Tab2.Tab.Handle=uitabgroup(...
    MainFig.Maintab.Tab4.Panel.Tab.Tab2.Panel.Handle,...
    'Position',[0.005 0.005 0.99 0.99]);
MainFig.Maintab.Tab4.Panel.Tab.Tab2.Tab.Tab1.Handle=uitab(...
    MainFig.Maintab.Tab4.Panel.Tab.Tab2.Tab.Handle,...
    'Title','Orbit Displacement [nm]');
MainFig.Maintab.Tab4.Panel.Tab.Tab2.Tab.Tab2.Handle=uitab(...
    MainFig.Maintab.Tab4.Panel.Tab.Tab2.Tab.Handle,...
    'Title','Run Length [µm]');
MainFig.Maintab.Tab4.Panel.Tab.Tab2.Tab.Tab3.Handle=uitab(...
    MainFig.Maintab.Tab4.Panel.Tab.Tab2.Tab.Handle,...
    'Title','Duration [s]');
MainFig.Maintab.Tab4.Panel.Tab.Tab2.Tab.Tab4.Handle=uitab(...
    MainFig.Maintab.Tab4.Panel.Tab.Tab2.Tab.Handle,...
    'Title','Movement Behaviour Pattern');
MainFig.Maintab.Tab4.Panel.Tab.Tab2.Tab.Tab5.Handle=uitab(...
    MainFig.Maintab.Tab4.Panel.Tab.Tab2.Tab.Handle,...
    'Title','Colocalization');

%Fill Tab "Orbit Displacement [nm]"
MainFig.Maintab.Tab4.Panel.Tab.Tab2.Tab.Tab1.Fig1=axes('Parent',MainFig.Maintab.Tab4.Panel.Tab.Tab2.Tab.Tab1.Handle,'Position',[0.05 0.1 0.9 0.8]);
MainFig.Maintab.Tab4.Panel.Tab.Tab2.Tab.Tab1.Fig1.Title.String='Orbit Displacement';
MainFig.Maintab.Tab4.Panel.Tab.Tab2.Tab.Tab1.Fig1.XLabel.String='Displacement [nm]';
MainFig.Maintab.Tab4.Panel.Tab.Tab2.Tab.Tab1.Fig1.YLabel.String='Normalized # of Events';


%Fill Tab "Run Length [µm]"
MainFig.Maintab.Tab4.Panel.Tab.Tab2.Tab.Tab2.Fig1=axes('Parent',...
    MainFig.Maintab.Tab4.Panel.Tab.Tab2.Tab.Tab2.Handle,'Position',[0.05 0.11 0.4 0.33]);
MainFig.Maintab.Tab4.Panel.Tab.Tab2.Tab.Tab2.Fig1.Title.String='Retrograde Slow';
MainFig.Maintab.Tab4.Panel.Tab.Tab2.Tab.Tab2.Fig1.XLabel.String='Run length [µm]';
MainFig.Maintab.Tab4.Panel.Tab.Tab2.Tab.Tab2.Fig1.YLabel.String='# of Events';
MainFig.Maintab.Tab4.Panel.Tab.Tab2.Tab.Tab2.Fig2=axes('Parent',...
    MainFig.Maintab.Tab4.Panel.Tab.Tab2.Tab.Tab2.Handle,'Position',[0.05 0.61 0.4 0.33]);
MainFig.Maintab.Tab4.Panel.Tab.Tab2.Tab.Tab2.Fig2.Title.String='Retrograde Fast';
MainFig.Maintab.Tab4.Panel.Tab.Tab2.Tab.Tab2.Fig2.XLabel.String='Run length [µm]';
MainFig.Maintab.Tab4.Panel.Tab.Tab2.Tab.Tab2.Fig2.YLabel.String='# of Events';
MainFig.Maintab.Tab4.Panel.Tab.Tab2.Tab.Tab2.Fig3=axes('Parent',...
    MainFig.Maintab.Tab4.Panel.Tab.Tab2.Tab.Tab2.Handle,'Position',[0.55 0.11 0.4 0.33]);
MainFig.Maintab.Tab4.Panel.Tab.Tab2.Tab.Tab2.Fig3.Title.String='Anterograde Slow';
MainFig.Maintab.Tab4.Panel.Tab.Tab2.Tab.Tab2.Fig3.XLabel.String='Run length [µm]';
MainFig.Maintab.Tab4.Panel.Tab.Tab2.Tab.Tab2.Fig3.YLabel.String='# of Events';
MainFig.Maintab.Tab4.Panel.Tab.Tab2.Tab.Tab2.Fig4=axes('Parent',...
    MainFig.Maintab.Tab4.Panel.Tab.Tab2.Tab.Tab2.Handle,'Position',[0.55 0.61 0.4 0.33]);
MainFig.Maintab.Tab4.Panel.Tab.Tab2.Tab.Tab2.Fig4.Title.String='Anterograde Fast';
MainFig.Maintab.Tab4.Panel.Tab.Tab2.Tab.Tab2.Fig4.XLabel.String='Run length [µm]';
MainFig.Maintab.Tab4.Panel.Tab.Tab2.Tab.Tab2.Fig4.YLabel.String='# of Events';


%Create Textboxes for Mean Values [µm]
MainFig.Maintab.Tab4.Panel.Tab.Tab2.Tab.Tab2.Text1=uicontrol(...
    MainFig.Maintab.Tab4.Panel.Tab.Tab2.Tab.Tab2.Handle,'Units','Normalized',...
    'Position', [0.35 0 0.1 0.05],'Style','text','String','Mean= ~ µm');
MainFig.Maintab.Tab4.Panel.Tab.Tab2.Tab.Tab2.Text2=uicontrol(...
    MainFig.Maintab.Tab4.Panel.Tab.Tab2.Tab.Tab2.Handle,'Units','Normalized',...
    'Position', [0.35 0.5 0.1 0.05],'Style','text','String','Mean= ~ µm');
MainFig.Maintab.Tab4.Panel.Tab.Tab2.Tab.Tab2.Text3=uicontrol(...
    MainFig.Maintab.Tab4.Panel.Tab.Tab2.Tab.Tab2.Handle,'Units','Normalized',...
    'Position', [0.85 0 0.1 0.05],'Style','text','String','Mean= ~ µm');
MainFig.Maintab.Tab4.Panel.Tab.Tab2.Tab.Tab2.Text4=uicontrol(...
    MainFig.Maintab.Tab4.Panel.Tab.Tab2.Tab.Tab2.Handle,'Units','Normalized',...
    'Position', [0.85 0.5 0.1 0.05],'Style','text','String','Mean= ~ µm');


%Fill Tab "Duration [s]"
%Create Figures for Duration [s]
MainFig.Maintab.Tab4.Panel.Tab.Tab2.Tab.Tab3.Fig1=axes('Parent',...
    MainFig.Maintab.Tab4.Panel.Tab.Tab2.Tab.Tab3.Handle,'Position',[0.05 0.11 0.4 0.33]);
MainFig.Maintab.Tab4.Panel.Tab.Tab2.Tab.Tab3.Fig1.Title.String='Retrograde Slow';
MainFig.Maintab.Tab4.Panel.Tab.Tab2.Tab.Tab3.Fig1.XLabel.String='Duration [s]';
MainFig.Maintab.Tab4.Panel.Tab.Tab2.Tab.Tab3.Fig1.YLabel.String='# of Events';
MainFig.Maintab.Tab4.Panel.Tab.Tab2.Tab.Tab3.Fig2=axes('Parent',...
    MainFig.Maintab.Tab4.Panel.Tab.Tab2.Tab.Tab3.Handle,'Position',[0.05 0.61 0.4 0.33]);
MainFig.Maintab.Tab4.Panel.Tab.Tab2.Tab.Tab3.Fig2.Title.String='Retrograde Fast';
MainFig.Maintab.Tab4.Panel.Tab.Tab2.Tab.Tab3.Fig2.XLabel.String='Duration [s]';
MainFig.Maintab.Tab4.Panel.Tab.Tab2.Tab.Tab3.Fig2.YLabel.String='# of Events';
MainFig.Maintab.Tab4.Panel.Tab.Tab2.Tab.Tab3.Fig3=axes('Parent',...
    MainFig.Maintab.Tab4.Panel.Tab.Tab2.Tab.Tab3.Handle,'Position',[0.55 0.11 0.4 0.33]);
MainFig.Maintab.Tab4.Panel.Tab.Tab2.Tab.Tab3.Fig3.Title.String='Anterograde Slow';
MainFig.Maintab.Tab4.Panel.Tab.Tab2.Tab.Tab3.Fig3.XLabel.String='Duration [s]';
MainFig.Maintab.Tab4.Panel.Tab.Tab2.Tab.Tab3.Fig3.YLabel.String='# of Events';
MainFig.Maintab.Tab4.Panel.Tab.Tab2.Tab.Tab3.Fig4=axes('Parent',...
    MainFig.Maintab.Tab4.Panel.Tab.Tab2.Tab.Tab3.Handle,'Position',[0.55 0.61 0.4 0.33]);
MainFig.Maintab.Tab4.Panel.Tab.Tab2.Tab.Tab3.Fig4.Title.String='Anterograde Fast';
MainFig.Maintab.Tab4.Panel.Tab.Tab2.Tab.Tab3.Fig4.XLabel.String='Duration [s]';
MainFig.Maintab.Tab4.Panel.Tab.Tab2.Tab.Tab3.Fig4.YLabel.String='# of Events';

%Create Textboxes for Mean Values [s]
MainFig.Maintab.Tab4.Panel.Tab.Tab2.Tab.Tab3.Text1=uicontrol(...
    MainFig.Maintab.Tab4.Panel.Tab.Tab2.Tab.Tab3.Handle,'Units','Normalized',...
    'Position', [0.35 0 0.1 0.05],'Style','text','String','Mean= ~ s');
MainFig.Maintab.Tab4.Panel.Tab.Tab2.Tab.Tab3.Text2=uicontrol(...
    MainFig.Maintab.Tab4.Panel.Tab.Tab2.Tab.Tab3.Handle,'Units','Normalized',...
    'Position', [0.35 0.5 0.1 0.05],'Style','text','String','Mean= ~ s');
MainFig.Maintab.Tab4.Panel.Tab.Tab2.Tab.Tab3.Text3=uicontrol(...
    MainFig.Maintab.Tab4.Panel.Tab.Tab2.Tab.Tab3.Handle,'Units','Normalized',...
    'Position', [0.85 0 0.1 0.05],'Style','text','String','Mean= ~ s');
MainFig.Maintab.Tab4.Panel.Tab.Tab2.Tab.Tab3.Text4=uicontrol(...
    MainFig.Maintab.Tab4.Panel.Tab.Tab2.Tab.Tab3.Handle,'Units','Normalized',...
    'Position', [0.85 0.5 0.1 0.05],'Style','text','String','Mean= ~ s');


%Fill "Tab Movement Behaviour Pattern"
MainFig.Maintab.Tab4.Panel.Tab.Tab2.Tab.Tab4.Panel.Handle=uipanel(...
    MainFig.Maintab.Tab4.Panel.Tab.Tab2.Tab.Tab4.Handle,'Position',[0 0 1 1],...
    'HandleVisibility','On');

%Table for Transition Propability
MainFig.Maintab.Tab4.Panel.Tab.Tab2.Tab.Tab4.Panel.Table1=...
    uitable(MainFig.Maintab.Tab4.Panel.Tab.Tab2.Tab.Tab4.Panel.Handle,...
    'Units','Normalized',...
    'Position',[0.005 0.75 0.36 0.22],...
    'Data',[0 0 0 0; 0 0 0 0; 0 0 0 0; 0 0 0 0;],...
    'ColumnName',{'End F. Retro','End F. Antero','End S. Retro','End S. Antero'},...
    'RowName',{'Start Fast Retro','Start Fast Antero','Start Slow Retro','Start Slow Antero'},...
    'ColumnWidth',{'auto' 'auto' 'auto' 'auto' });
MainFig.Maintab.Tab4.Panel.Tab.Tab2.Tab.Tab4.Panel.Table1.Position(3) = ...
    MainFig.Maintab.Tab4.Panel.Tab.Tab2.Tab.Tab4.Panel.Table1.Extent(3);
MainFig.Maintab.Tab4.Panel.Tab.Tab2.Tab.Tab4.Panel.Table1.Position(4) = ...
    MainFig.Maintab.Tab4.Panel.Tab.Tab2.Tab.Tab4.Panel.Table1.Extent(4);
%Description for table Transition Propability
MainFig.Maintab.Tab4.Panel.Tab.Tab2.Tab.Tab4.Panel.Text1=uicontrol(...
    MainFig.Maintab.Tab4.Panel.Tab.Tab2.Tab.Tab4.Panel.Handle,'Units','Normalized',...
    'Position', [0.01 0.92 0.125 0.03],'Style','text','String','Transition Propability',...
    'FontSize',10);

%Table for Transition Time
MainFig.Maintab.Tab4.Panel.Tab.Tab2.Tab.Tab4.Panel.Table2=...
    uitable(MainFig.Maintab.Tab4.Panel.Tab.Tab2.Tab.Tab4.Panel.Handle,...
    'Units','Normalized',...
    'Position',[0.501 0.75 0.36 0.22],...
    'Data',[0 0 0 0; 0 0 0 0; 0 0 0 0; 0 0 0 0;],...
    'ColumnName',{'End F. Retro','End F. Antero','End S. Retro','End S. Antero'},...
    'RowName',{'Start Fast Retro','Start Fast Antero','Start Slow Retro','Start Slow Antero'},...
    'ColumnWidth',{'auto' 'auto' 'auto' 'auto' },...
    'CellSelectionCallback',@Summary_Histogram);
MainFig.Maintab.Tab4.Panel.Tab.Tab2.Tab.Tab4.Panel.Table2.Position(3) = ...
    MainFig.Maintab.Tab4.Panel.Tab.Tab2.Tab.Tab4.Panel.Table2.Extent(3);
MainFig.Maintab.Tab4.Panel.Tab.Tab2.Tab.Tab4.Panel.Table2.Position(4) = ...
    MainFig.Maintab.Tab4.Panel.Tab.Tab2.Tab.Tab4.Panel.Table2.Extent(4);
%Description for table Transition TIme
MainFig.Maintab.Tab4.Panel.Tab.Tab2.Tab.Tab4.Panel.Text1=uicontrol(...
    MainFig.Maintab.Tab4.Panel.Tab.Tab2.Tab.Tab4.Panel.Handle,'Units','Normalized',...
    'Position', [0.501 0.92 0.125 0.03],'Style','text','String','Transition Time [s]',...
    'FontSize',10);


%Create Figure to plot Histograms
MainFig.Maintab.Tab4.Panel.Tab.Tab2.Tab.Tab4.Panel.Fig1=axes('Parent',...
    MainFig.Maintab.Tab4.Panel.Tab.Tab2.Tab.Tab4.Panel.Handle,'Position',[0.05 0.05 0.9 0.6],...
    'xlim',[-0.5 40.5],...
    'Box','on');
%Description for Histogram
MainFig.Maintab.Tab4.Panel.Tab.Tab2.Tab.Tab4.Panel.Text3=uicontrol(...
    MainFig.Maintab.Tab4.Panel.Tab.Tab2.Tab.Tab4.Panel.Handle,'Units','Normalized',...
    'Position', [0.05 0.653 0.35 0.05],'Style','text','String','Transition Time Histogram (Click Transition Time to Plot)',...
    'FontSize',10);


%Fill Tab "Colocalization"
MainFig.Maintab.Tab4.Panel.Tab.Tab2.Tab.Tab5.Panel.Handle=uipanel(...
    MainFig.Maintab.Tab4.Panel.Tab.Tab2.Tab.Tab5.Handle,'Position',[0 0 1 1],...
    'HandleVisibility','On');

%Orbit Ratio
MainFig.Maintab.Tab4.Panel.Tab.Tab2.Tab.Tab5.Panel.Fig1=axes('Parent',...
    MainFig.Maintab.Tab4.Panel.Tab.Tab2.Tab.Tab5.Panel.Handle,'Position',[0.05 0.05 0.4 0.35],...
    'xlim',[-0.5 40.5],...
    'Box','on');
MainFig.Maintab.Tab4.Panel.Tab.Tab2.Tab.Tab5.Panel.Text1=uicontrol(...
    MainFig.Maintab.Tab4.Panel.Tab.Tab2.Tab.Tab5.Panel.Handle,'Units','Normalized',...
    'Position', [0.025 0.42 0.125 0.03],'Style','text','String','Orbit Ratio',...
    'FontSize',10);

%Phases Ratio
MainFig.Maintab.Tab4.Panel.Tab.Tab2.Tab.Tab5.Panel.Fig2=axes('Parent',...
    MainFig.Maintab.Tab4.Panel.Tab.Tab2.Tab.Tab5.Panel.Handle,'Position',[0.55 0.05 0.4 0.35],...
    'xlim',[-0.5 40.5],...
    'Box','on');
MainFig.Maintab.Tab4.Panel.Tab.Tab2.Tab.Tab5.Panel.Text2=uicontrol(...
    MainFig.Maintab.Tab4.Panel.Tab.Tab2.Tab.Tab5.Panel.Handle,'Units','Normalized',...
    'Position', [0.525 0.42 0.125 0.03],'Style','text','String','Phases Ratio',...
    'FontSize',10);

%Tracks/Mito Orbits
MainFig.Maintab.Tab4.Panel.Tab.Tab2.Tab.Tab5.Panel.Fig3=axes('Parent',...
    MainFig.Maintab.Tab4.Panel.Tab.Tab2.Tab.Tab5.Panel.Handle,'Position',[0.05 0.55 0.4 0.35],...
    'xlim',[-0.5 40.5],...
    'Box','on');
MainFig.Maintab.Tab4.Panel.Tab.Tab2.Tab.Tab5.Panel.Text3=uicontrol(...
    MainFig.Maintab.Tab4.Panel.Tab.Tab2.Tab.Tab5.Panel.Handle,'Units','Normalized',...
    'Position', [0.025 0.92 0.125 0.03],'Style','text','String','Tracks/Mito Orbits',...
    'FontSize',10);

%Tracks/Mito Phases
MainFig.Maintab.Tab4.Panel.Tab.Tab2.Tab.Tab5.Panel.Fig4=axes('Parent',...
    MainFig.Maintab.Tab4.Panel.Tab.Tab2.Tab.Tab5.Panel.Handle,'Position',[0.55 0.55 0.4 0.35],...
    'xlim',[-0.5 40.5],...
    'Box','on');
MainFig.Maintab.Tab4.Panel.Tab.Tab2.Tab.Tab5.Panel.Text4=uicontrol(...
    MainFig.Maintab.Tab4.Panel.Tab.Tab2.Tab.Tab5.Panel.Handle,'Units','Normalized',...
    'Position', [0.525 0.92 0.125 0.03],'Style','text','String','Tracks/Mito Phases',...
    'FontSize',10);

%% Fill Tab "Plot Tracking Position In Video"
MainFig.Maintab.Tab5.Panel.Handle=uipanel('Parent',MainFig.Maintab.Tab5.Handle,'Position',[0 0 1 1]);

%Create Axes to Plot Video Frames
MainFig.Maintab.Tab5.Panel.Fig1=axes('Parent',MainFig.Maintab.Tab5.Panel.Handle,...
    'Position',[0.525 0.225 0.455 0.75],...
    'Box','On',...
    'ButtonDownFcn',@Load_Video);
MainFig.Maintab.Tab5.Panel.Fig1_Image=image(ones(512,512,3));
MainFig.Maintab.Tab5.Panel.Fig1_Image.HitTest = 'off';
MainFig.Maintab.Tab5.Panel.Fig1.ButtonDownFcn = @Video_Controls;
set(MainFig.Maintab.Tab5.Panel.Fig1);
% Create Buttons to Play and move for and backward one Frame
%Play Button
MainFig.Maintab.Tab5.Panel.Play_Button= uicontrol(MainFig.Maintab.Tab5.Handle,...
    'Style','togglebutton','String','Play/Pause','Units','Normalized','Position',[0.7 0.08 0.1 0.05],...
    'HandleVisibility','off','Callback',@Video_Controls);

%Slider
MainFig.Maintab.Tab5.Panel.Slider= uicontrol(MainFig.Maintab.Tab5.Handle,...
    'Style','slider','String','Slider','Units','Normalized','Position',[0.525 0.15 0.455 0.02],...
    'HandleVisibility','off','Callback',@Video_Controls);

%Forward Button
MainFig.Maintab.Tab5.Panel.Forward= uicontrol(MainFig.Maintab.Tab5.Handle,...
    'Style','pushbutton','String','>','Units','Normalized','Position',[0.81 0.08 0.05 0.05],...
    'HandleVisibility','off','Callback',@Video_Controls);

%Backward Button
MainFig.Maintab.Tab5.Panel.Forward= uicontrol(MainFig.Maintab.Tab5.Handle,...
    'Style','pushbutton','String','<','Units','Normalized','Position',[0.64 0.08 0.05 0.05],...
    'HandleVisibility','off','Callback',@Video_Controls);

%Textbox for Frame Time
MainFig.Maintab.Tab5.Panel.Frame_Rate_Edit=uicontrol(MainFig.Maintab.Tab5.Handle,...
    'Units','Normalized','Position',[0.525 0.01 0.1 0.025],...
    'Style','Edit','String','500');
MainFig.Maintab.Tab5.Panel.Frame_Rate_Static=uicontrol(MainFig.Maintab.Tab5.Handle,...
    'Units','Normalized','Position',[0.525 0.04 0.1 0.025],...
    'Style','Text','String','Frame Time [ms]');

%Uibutton Group for Play Speed
MainFig.Maintab.Tab5.Panel.Videospeed.Handle=uibuttongroup(MainFig.Maintab.Tab5.Panel.Handle, ...
    'Units','Normalized','Position', [0.65 0.01 0.2 0.05], ...
    'Title', 'Video Speed');
MainFig.Maintab.Tab5.Panel.Videospeed.Select1= uicontrol(MainFig.Maintab.Tab5.Panel.Videospeed.Handle,...
    'Style','radiobutton','String','1x','Units','Normalized','Position',[0.01 0.01 0.24 0.9],...
    'HandleVisibility','off');
MainFig.Maintab.Tab5.Panel.Videospeed.Select2= uicontrol(MainFig.Maintab.Tab5.Panel.Videospeed.Handle,...
    'Style','radiobutton','String','4x','Units','Normalized','Position',[0.25 0.01 0.24 0.9],...
    'HandleVisibility','off');
MainFig.Maintab.Tab5.Panel.Videospeed.Select3= uicontrol(MainFig.Maintab.Tab5.Panel.Videospeed.Handle,...
    'Style','radiobutton','String','16x','Units','Normalized','Position',[0.50 0.01 0.24 0.9],...
    'HandleVisibility','off');
MainFig.Maintab.Tab5.Panel.Videospeed.Select4= uicontrol(MainFig.Maintab.Tab5.Panel.Videospeed.Handle,...
    'Style','radiobutton','String','64x','Units','Normalized','Position',[0.75 0.01 0.24 0.9],...
    'HandleVisibility','off');

%Textbox for Timestamp
MainFig.Maintab.Tab5.Panel.CurrentTime_Edit=uicontrol(MainFig.Maintab.Tab5.Handle,...
    'Units','Normalized','Position',[0.88 0.01 0.1 0.025],...
    'Style','Text','String','0');
MainFig.Maintab.Tab5.Panel.CurrentTime_Static=uicontrol(MainFig.Maintab.Tab5.Handle,...
    'Units','Normalized','Position',[0.88 0.04 0.1 0.025],...
    'Style','Text','String','Elapsed Time [s]');

%Unload Video
MainFig.Maintab.Tab5.Panel.UnloadVideo= uicontrol(MainFig.Maintab.Tab5.Handle,...
    'Style','pushbutton','String','Unload Video','Units','Normalized','Position',[0.88 0.08 0.1 0.05],...
    'HandleVisibility','off','Callback',@Video_Controls);

%Panel for Video Settings
MainFig.Maintab.Tab5.Panel.Videopanel.Handle=uipanel(MainFig.Maintab.Tab5.Handle,...
    'Position',[0.01 0.51 0.48 0.48],...
    'Title','Video Settings');

%Panel for XY Shift
MainFig.Maintab.Tab5.Panel.Videopanel.XYShiftpanel.Handle=uipanel(MainFig.Maintab.Tab5.Panel.Videopanel.Handle,...
    'Position',[0.51 0.41 0.48 0.58],...
    'Title','Adjust XY Shift');

%Buttons for XY Shift
MainFig.Maintab.Tab5.Panel.Videopanel.XYShiftpanel.PlusX= uicontrol(MainFig.Maintab.Tab5.Panel.Videopanel.XYShiftpanel.Handle,...
    'Style','pushbutton','String','+ X','Units','Normalized','Position',[0.55 0.3 0.3 0.18],...
    'HandleVisibility','off','Callback',@Video_Settings_Controls);
MainFig.Maintab.Tab5.Panel.Videopanel.XYShiftpanel.MinusX= uicontrol(MainFig.Maintab.Tab5.Panel.Videopanel.XYShiftpanel.Handle,...
    'Style','pushbutton','String','- X','Units','Normalized','Position',[0.15 0.3 0.3 0.18],...
    'HandleVisibility','off','Callback',@Video_Settings_Controls);
MainFig.Maintab.Tab5.Panel.Videopanel.XYShiftpanel.PlusY= uicontrol(MainFig.Maintab.Tab5.Panel.Videopanel.XYShiftpanel.Handle,...
    'Style','pushbutton','String','+ Y','Units','Normalized','Position',[0.35 0.5 0.3 0.18],...
    'HandleVisibility','off','Callback',@Video_Settings_Controls);
MainFig.Maintab.Tab5.Panel.Videopanel.XYShiftpanel.MinusX= uicontrol(MainFig.Maintab.Tab5.Panel.Videopanel.XYShiftpanel.Handle,...
    'Style','pushbutton','String','- Y','Units','Normalized','Position',[0.35 0.08 0.3 0.18],...
    'HandleVisibility','off','Callback',@Video_Settings_Controls);

%Textfield for XYshift.
MainFig.Maintab.Tab5.Panel.Videopanel.XYShiftpanel.XShift_Edit=uicontrol(MainFig.Maintab.Tab5.Panel.Videopanel.XYShiftpanel.Handle,...
    'Units','Normalized','Position',[0.075 0.75 0.35 0.1],...
    'Style','Edit','String','0');
MainFig.Maintab.Tab5.Panel.Videopanel.XYShiftpanel.XShift_Static=uicontrol(MainFig.Maintab.Tab5.Panel.Videopanel.XYShiftpanel.Handle,...
    'Units','Normalized','Position',[0.075 0.86 0.35 0.1],...
    'Style','Text','String','X Shift');
MainFig.Maintab.Tab5.Panel.Videopanel.XYShiftpanel.YShift_Edit=uicontrol(MainFig.Maintab.Tab5.Panel.Videopanel.XYShiftpanel.Handle,...
    'Units','Normalized','Position',[0.575 0.75 0.35 0.1],...
    'Style','Edit','String','0');
MainFig.Maintab.Tab5.Panel.Videopanel.XYShiftpanel.YShift_Static=uicontrol(MainFig.Maintab.Tab5.Panel.Videopanel.XYShiftpanel.Handle,...
    'Units','Normalized','Position',[0.575 0.86 0.35 0.1],...
    'Style','Text','String','Y Shift');



%Panel for Frameshift
MainFig.Maintab.Tab5.Panel.Videopanel.Frameshift.Handle=uipanel(MainFig.Maintab.Tab5.Panel.Videopanel.Handle,...
    'Position',[0.51 0.01 0.48 0.38],...
    'Title','Adjust Frame Shift');

%Buttons for Frame Shift
MainFig.Maintab.Tab5.Panel.Videopanel.Frameshift.FramePlus= uicontrol(MainFig.Maintab.Tab5.Panel.Videopanel.Frameshift.Handle,...
    'Style','pushbutton','String','>','Units','Normalized','Position',[0.55 0.1 0.4 0.3],...
    'HandleVisibility','off','Callback',@Video_Settings_Controls);
MainFig.Maintab.Tab5.Panel.Videopanel.Frameshift.FramePlusMinus= uicontrol(MainFig.Maintab.Tab5.Panel.Videopanel.Frameshift.Handle,...
    'Style','pushbutton','String','<','Units','Normalized','Position',[0.05 0.1 0.4 0.3],...
    'HandleVisibility','off','Callback',@Video_Settings_Controls);

%Textfield for Frameshift
MainFig.Maintab.Tab5.Panel.Videopanel.Frameshift.Frameshift_Edit=uicontrol(MainFig.Maintab.Tab5.Panel.Videopanel.Frameshift.Handle,...
    'Units','Normalized','Position',[0.325 0.6 0.35 0.2],...
    'Style','Edit','String','0');
MainFig.Maintab.Tab5.Panel.Videopanel.Frameshift.Frameshift_Static=uicontrol(MainFig.Maintab.Tab5.Panel.Videopanel.Frameshift.Handle,...
    'Units','Normalized','Position',[0.325 0.81 0.35 0.2],...
    'Style','Text','String','Frame Shift');



%Panel for Transfermatrix creation
MainFig.Maintab.Tab5.Panel.Videopanel.TransfermatrixVideoTrajectories.Handle=uipanel(MainFig.Maintab.Tab5.Panel.Videopanel.Handle,...
    'Position',[0.01 0.01 0.48 0.23],...
    'Title','Create Transfermatrix + Video Trajectory');

%Create Button to Create Transfermatrix
MainFig.Maintab.Tab5.Panel.Videopanel.TransfermatrixVideoTrajectories.Load_Mapping_Calibration= uicontrol(MainFig.Maintab.Tab5.Panel.Videopanel.TransfermatrixVideoTrajectories.Handle,...
    'Style','pushbutton','String','Load Mapping Video','Units','Normalized','Position',[0.05 0.2 0.5 0.6],...
    'HandleVisibility','off','Callback',@Create_Transfermatrix);

%Create Textfield for Scaling Factor for Transfermatrix
MainFig.Maintab.Tab5.Panel.Videopanel.TransfermatrixVideoTrajectories.Scaling_Factor_Edit=uicontrol(MainFig.Maintab.Tab5.Panel.Videopanel.TransfermatrixVideoTrajectories.Handle,...
    'Units','Normalized','Position',[0.62 0.2 0.35 0.3],...
    'Style','Edit','String','0.8');
MainFig.Maintab.Tab5.Panel.Videopanel.TransfermatrixVideoTrajectories.Scaling_Factor_Static=uicontrol(MainFig.Maintab.Tab5.Panel.Videopanel.TransfermatrixVideoTrajectories.Handle,...
    'Units','Normalized','Position',[0.62 0.5 0.35 0.3],...
    'Style','Text','String','Scaling Factor');


%Panel for Video Mode
MainFig.Maintab.Tab5.Panel.Videopanel.VideoMode.Handle=uipanel(MainFig.Maintab.Tab5.Panel.Videopanel.Handle,...
    'Position',[0.01 0.26 0.48 0.73],...
    'Title','Select Video Mode');

%Buttons to choose Overlay Mode
MainFig.Maintab.Tab5.Panel.Videopanel.VideoMode.Overlay.Handle=uibuttongroup(MainFig.Maintab.Tab5.Panel.Videopanel.VideoMode.Handle, ...
    'Units','Normalized','Position', [0.025 0.55 0.95 0.45],...
    'SelectionChangedFcn',@Video_Settings_Controls);
MainFig.Maintab.Tab5.Panel.Videopanel.VideoMode.Overlay.Select1= uicontrol(MainFig.Maintab.Tab5.Panel.Videopanel.VideoMode.Overlay.Handle,...
    'Style','radiobutton','String','Crosshair without Population Information','Units','Normalized','Position',[0.025 0.76 0.95 0.24],...
    'HandleVisibility','off');
MainFig.Maintab.Tab5.Panel.Videopanel.VideoMode.Overlay.Select2= uicontrol(MainFig.Maintab.Tab5.Panel.Videopanel.VideoMode.Overlay.Handle,...
    'Style','radiobutton','String','Crosshair with Population Information','Units','Normalized','Position',[0.025 0.51 0.95 0.24],...
    'HandleVisibility','off');
MainFig.Maintab.Tab5.Panel.Videopanel.VideoMode.Overlay.Select3= uicontrol(MainFig.Maintab.Tab5.Panel.Videopanel.VideoMode.Overlay.Handle,...
    'Style','radiobutton','String','Trailing Points with Population Information','Units','Normalized','Position',[0.026 0.25 0.95 0.24],...
    'HandleVisibility','off');
MainFig.Maintab.Tab5.Panel.Videopanel.VideoMode.Overlay.Select4= uicontrol(MainFig.Maintab.Tab5.Panel.Videopanel.VideoMode.Overlay.Handle,...
    'Style','radiobutton','String','Cross with Red = Mito Green = No Mito','Units','Normalized','Position',[0.025 0.01 0.95 0.24],...
    'HandleVisibility','off');

%Buttons to choose between raw image or bw mode
MainFig.Maintab.Tab5.Panel.Videopanel.VideoMode.Image_Mode.Handle=uibuttongroup(MainFig.Maintab.Tab5.Panel.Videopanel.VideoMode.Handle, ...
    'Units','Normalized','Position', [0.025 0.375 0.95 0.15],...
    'SelectionChangedFcn',@Video_Settings_Controls);
MainFig.Maintab.Tab5.Panel.Videopanel.VideoMode.Image_Mode.Select1= uicontrol(MainFig.Maintab.Tab5.Panel.Videopanel.VideoMode.Image_Mode.Handle,...
    'Style','radiobutton','String','Raw Image','Units','Normalized','Position',[0.025 0.025 0.45 0.95],...
    'HandleVisibility','off');
MainFig.Maintab.Tab5.Panel.Videopanel.VideoMode.Image_Mode.Select2= uicontrol(MainFig.Maintab.Tab5.Panel.Videopanel.VideoMode.Image_Mode.Handle,...
    'Style','radiobutton','String','BW Image','Units','Normalized','Position',[0.525 0.025 0.45 0.95],...
    'HandleVisibility','off');

%Buttons to transpose image
%Buttons to choose between raw image or bw mode
MainFig.Maintab.Tab5.Panel.Videopanel.VideoMode.Transpose_Image.Handle=uibuttongroup(MainFig.Maintab.Tab5.Panel.Videopanel.VideoMode.Handle, ...
    'Units','Normalized','Position', [0.025 0.2 0.95 0.15],...
    'SelectionChangedFcn',@Video_Settings_Controls);
MainFig.Maintab.Tab5.Panel.Videopanel.VideoMode.Transpose_Image.Select1= uicontrol(MainFig.Maintab.Tab5.Panel.Videopanel.VideoMode.Transpose_Image.Handle,...
    'Style','radiobutton','String','Normal','Units','Normalized','Position',[0.025 0.025 0.45 0.95],...
    'HandleVisibility','off');
MainFig.Maintab.Tab5.Panel.Videopanel.VideoMode.Transpose_Image.Select2= uicontrol(MainFig.Maintab.Tab5.Panel.Videopanel.VideoMode.Transpose_Image.Handle,...
    'Style','radiobutton','String','Transposed','Units','Normalized','Position',[0.525 0.025 0.45 0.95],...
    'HandleVisibility','off');


%Button to Create RGB Video
MainFig.Maintab.Tab5.Panel.Videopanel.VideoMode.Render_Video= uicontrol(MainFig.Maintab.Tab5.Panel.Videopanel.VideoMode.Handle,...
    'Style','pushbutton','String','Render Video','Units','Normalized','Position',[0.25 0.025 0.5 0.15],...
    'HandleVisibility','off','Callback',@Video_Settings_Controls);







%Panel for Colocalization Analysis
MainFig.Maintab.Tab5.Panel.Colocalizationpanel.Handle=uipanel(MainFig.Maintab.Tab5.Handle,...
    'Position',[0.01 0.01 0.48 0.48],...
    'Title','Colocalization Analysis');



%Tabgroup for Results
MainFig.Maintab.Tab5.Panel.Colocalizationpanel.Tab.Handle=...
    uitabgroup(MainFig.Maintab.Tab5.Panel.Colocalizationpanel.Handle,'Position',[0.01 0.01 0.98 0.9]);
MainFig.Maintab.Tab5.Panel.Colocalizationpanel.Tab.Tab1.Handle=uitab(...
    MainFig.Maintab.Tab5.Panel.Colocalizationpanel.Tab.Handle,'Title','Orbit Ratio');
MainFig.Maintab.Tab5.Panel.Colocalizationpanel.Tab.Tab2.Handle=uitab(...
    MainFig.Maintab.Tab5.Panel.Colocalizationpanel.Tab.Handle,'Title','Phases Ratio');
MainFig.Maintab.Tab5.Panel.Colocalizationpanel.Tab.Tab3.Handle=uitab(...
    MainFig.Maintab.Tab5.Panel.Colocalizationpanel.Tab.Handle,'Title','Mito/Track Orbits');
MainFig.Maintab.Tab5.Panel.Colocalizationpanel.Tab.Tab4.Handle=uitab(...
    MainFig.Maintab.Tab5.Panel.Colocalizationpanel.Tab.Handle,'Title','Mito/Track Phases');

%Panels in Tabs
MainFig.Maintab.Tab5.Panel.Colocalizationpanel.Tab.Tab1.Panel.Handle=uipanel(...
    MainFig.Maintab.Tab5.Panel.Colocalizationpanel.Tab.Tab1.Handle,...
    'Position',[0.01 0.01 0.98 0.98]);
MainFig.Maintab.Tab5.Panel.Colocalizationpanel.Tab.Tab2.Panel.Handle=uipanel(...
    MainFig.Maintab.Tab5.Panel.Colocalizationpanel.Tab.Tab2.Handle,...
    'Position',[0.01 0.01 0.98 0.98]);
MainFig.Maintab.Tab5.Panel.Colocalizationpanel.Tab.Tab3.Panel.Handle=uipanel(...
    MainFig.Maintab.Tab5.Panel.Colocalizationpanel.Tab.Tab3.Handle,...
    'Position',[0.01 0.01 0.98 0.98]);
MainFig.Maintab.Tab5.Panel.Colocalizationpanel.Tab.Tab4.Panel.Handle=uipanel(...
    MainFig.Maintab.Tab5.Panel.Colocalizationpanel.Tab.Tab4.Handle,...
    'Position',[0.01 0.01 0.98 0.98]);

%Axes in Panels
MainFig.Maintab.Tab5.Panel.Colocalizationpanel.Tab.Tab1.Panel.Axes=...
    axes('Parent',MainFig.Maintab.Tab5.Panel.Colocalizationpanel.Tab.Tab1.Panel.Handle,...
    'Position',[0.01 0.01 0.98 0.98],...
    'Box','On',...
    'YTickLabel','',...
    'XTickLabel','');
MainFig.Maintab.Tab5.Panel.Colocalizationpanel.Tab.Tab2.Panel.Axes=...
    axes('Parent',MainFig.Maintab.Tab5.Panel.Colocalizationpanel.Tab.Tab2.Panel.Handle,...
    'Position',[0.01 0.01 0.98 0.98],...
    'Box','On',...
    'YTickLabel','',...
    'XTickLabel','');
MainFig.Maintab.Tab5.Panel.Colocalizationpanel.Tab.Tab3.Panel.Axes=...
    axes('Parent',MainFig.Maintab.Tab5.Panel.Colocalizationpanel.Tab.Tab3.Panel.Handle,...
    'Position',[0.01 0.01 0.98 0.98],...
    'Box','On',...
    'YTickLabel','',...
    'XTickLabel','');
MainFig.Maintab.Tab5.Panel.Colocalizationpanel.Tab.Tab4.Panel.Axes=...
    axes('Parent',MainFig.Maintab.Tab5.Panel.Colocalizationpanel.Tab.Tab4.Panel.Handle,...
    'Position',[0.01 0.01 0.98 0.98],...
    'Box','On',...
    'YTickLabel','',...
    'XTickLabel','');

%Button to Start Colocalization Analysis
MainFig.Maintab.Tab5.Panel.Colocalizationpanel.Start_Colocalization= uicontrol(MainFig.Maintab.Tab5.Panel.Colocalizationpanel.Handle,...
    'Style','pushbutton','String','Start Colocalization','Units','Normalized','Position',[0.4 0.925 0.2 0.075],...
    'HandleVisibility','off','Callback',@Start_Colocalization);

%Textfield for Startpoint Colocalization Analysis
MainFig.Maintab.Tab5.Panel.Colocalizationpanel.Start_Static=uicontrol(MainFig.Maintab.Tab5.Panel.Colocalizationpanel.Handle,...
    'Units','Normalized','Position',[0.68 0.91 0.15 0.08],...
    'Style','Text','String','Start Long Range Phase [?]');
MainFig.Maintab.Tab5.Panel.Colocalizationpanel.Start_Edit=uicontrol(MainFig.Maintab.Tab5.Panel.Colocalizationpanel.Handle,...
    'Units','Normalized','Position',[0.68 0.85 0.15 0.05],...
    'Style','Edit','String','0');

%Textfield for Endpoint Colocalization Analysis
MainFig.Maintab.Tab5.Panel.Colocalizationpanel.End_Static=uicontrol(MainFig.Maintab.Tab5.Panel.Colocalizationpanel.Handle,...
    'Units','Normalized','Position',[0.84 0.91 0.15 0.08],...
    'Style','Text','String','End Long Range Phase [?]');
MainFig.Maintab.Tab5.Panel.Colocalizationpanel.End_Edit=uicontrol(MainFig.Maintab.Tab5.Panel.Colocalizationpanel.Handle,...
    'Units','Normalized','Position',[0.84 0.85 0.15 0.05],...
    'Style','Edit','String','0');

%% Fill Tab "Analyse Repetitve Data"
MainFig.Maintab.Tab6.Panel.Handle=uipanel('Parent',MainFig.Maintab.Tab6.Handle,'Position',[0 0 1 1]);

%Create uitab
MainFig.Maintab.Tab6.Panel.Tab.Handle=uitabgroup(MainFig.Maintab.Tab6.Panel.Handle,'Position',[0.005 0.005 0.99 0.99]);
MainFig.Maintab.Tab6.Panel.Tab.Tab1.Handle=uitab(MainFig.Maintab.Tab6.Panel.Tab.Handle,'Title','Load Data');
MainFig.Maintab.Tab6.Panel.Tab.Tab2.Handle=uitab(MainFig.Maintab.Tab6.Panel.Tab.Handle,'Title','Results');

% Fill Tab "Load Data"
%Create Table
MainFig.Maintab.Tab6.Panel.Tab.Tab1.Table=uitable(MainFig.Maintab.Tab6.Panel.Tab.Tab1.Handle,...
    'Units','Normalized',...
    'Position',[0.005 0.105 0.99 0.89],...
    'ColumnName',{'Filename','Use File','Direction','Trajectory Length [µm]'},...
    'Data',{'Filename',false, 'Retrograde/Anterograde' '0'},...
    'ColumnEditable',[false true false false],...
    'ColumnWidth',{800 'auto' 200 200});

%Create Button "Select Folder"
MainFig.Maintab.Tab6.Panel.Tab.Tab1.Load=uicontrol(MainFig.Maintab.Tab6.Panel.Tab.Tab1.Handle,...
    'Style','pushbutton','String','Select Folder', ...
    'Units','Normalized','Position', [0.1 0.0225 0.15 0.05])%, ...
%     'Callback',@Select_Folder);

%Create Button "Summarize Data"
MainFig.Maintab.Tab6.Panel.Tab.Tab1.Load=uicontrol(MainFig.Maintab.Tab6.Panel.Tab.Tab1.Handle,...
    'Style','pushbutton','String','Load Data', ...
    'Units','Normalized','Position', [0.28 0.0225 0.15 0.05]);%, ...
%     'Callback');

%Create Button "Save Summary"
MainFig.Maintab.Tab4.Panel.Tab.Tab1.Load=uicontrol(MainFig.Maintab.Tab4.Panel.Tab.Tab1.Handle,...
    'Style','pushbutton','String','Save Summary', ...
    'Units','Normalized','Position', [0.46 0.0225 0.15 0.05]);%, ...
%     'Callback',@Save_Summary);


